### ISSUE TITLE
shebang

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-defining-schema-with-sqlalchemy#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/205983?module_item_id=472696

### Concern

Persisting the Schema: Students will probably not know what a shebang is at this point and `chmod +x` will probably confuse them. I ran through the labs a second time but didn't see it brought up in previous labs. 

### Suggested Changes

A lab on shebang might be a good addition to the Configuring Python Applications Module.

**Comment by professor-ben** [comment]
I agree that this should go into configuring apps. I'm going to leave this open and assign to Prabhdip.

Thanks!
