### ISSUE TITLE
Not Able To Create DB Inside A Directory

### ISSUE THREAD

**Issue by miShelbyT** [learn-co-curriculum/python-p3-defining-schema-with-sqlalchemy#5]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/205983?module_item_id=472696

### Concern

Went through the code with Ben in sqlalchemy_sandbox.py. My system allows me to create a database file at the root level but not inside an inner directory (in our case, from inside the lib folder, creating the database file inside of an existing db directory. 

Specifically, this correctly creates the database when you run the sandbox file: `engine = create_engine('sqlite:///my_database.db')` but this does not: `engine = create_engine('sqlite:///db/my_database.db')`

**Comment by professor-ben** [comment]
I believe I fixed this earlier today. I will be keeping a close eye on this one, though.
