### ISSUE TITLE
Possible sqlalchemy version issue

### ISSUE THREAD

**Issue by QSissler** [learn-co-curriculum/python-p3-defining-schema-with-sqlalchemy#8]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/205983?module_item_id=472696

### Concern

After running pipenv install and pipenv shell, the sqlalchemy imports in the sqlalchemy_sandbox.py file have yellow squiggles and "Import "sqlalchemy" could not be resolved from source" message.
<img width="602" alt="Screen Shot 2023-01-27 at 5 57 03 PM" src="https://user-images.githubusercontent.com/81705554/215221736-aec7d94b-b72f-4a01-8610-108a4ec83a3a.png">

I continue with the code along, it did work correctly it seems but when running the "lib/sqlalchemy_sandbox.py" command the following warning was given:
<img width="940" alt="Screen Shot 2023-01-27 at 5 58 46 PM" src="https://user-images.githubusercontent.com/81705554/215221873-008c8389-2e8c-439a-9e5d-81c079fedcdb.png">

It looks like sqlalchemy just released version 2.0 yesterday so I am wondering if that is what this issue is related to.

### Additional Context

https://www.sqlalchemy.org/blog/2023/01/26/sqlalchemy-2.0.0-released/

**Comment by professor-ben** [comment]
This typically happens when you open VSCode from a lower directory than the one containing the Pipfile. We hardcode the version to 1.4.1, so there shouldn't be conflicts there (hopefully!)

Is your code running OK?
